import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Headers from "@/components/Headers";
import PageTransition from "@/components/PageTransition";
import Stairtransition from "@/components/Stairtransition";

const jetBrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--font-jetBrainsMono",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetBrainsMono.variable}>
        <Headers />
        <Stairtransition />
        <PageTransition>{children}</PageTransition>
      </body>
    </html>
  );
}
